### PR TITLE
Fix Systemd svc start error: "Error: unable to create mountpoint"

### PR DESCRIPTION
**Pull request by Billy99**
Resolves: #140

Signed-off-by: Billy McFall <22157057+Billy99@users.noreply.github.com>

### CODE REVIEW

**Comment by nerdalert** [comment]
@Billy99 that did it, thanks 🎉

**Review by nerdalert — COMMENTED** [review]
@Billy99 that did it, thanks 🎉

**Comment by Billy99** [comment]
Which docs go in `docs/admin/` and which go in `docs/developer/`?

**Comment by astoycos** [comment]
@Billy99 Shouldn't this all be admin docs? The general point of the doc is how to configure bpfd correctly, which in a normal Cloud environment an "admin" would always be doing. 

Developer docs are probably more pubilc API related things IMO, but If there's other ideas I'm happy to hear them

**Comment by Billy99** [comment]
> Shouldn't this all be admin docs?
I couldn't tell what went where. Not sure we even need two docs directories for bpfd, but happy to move. I'll move in a follow-up PR.

**Comment by astoycos** [comment]
It's a good point... Really the only docs I would see Admin's needing would be those related to the APIs bpfd exposes i.e using bpfctl, and the specs to which we align with.  Otherwise I think this is GTG for now we can address where the docs are living (as a whole) in a follow up PR :)

**Pull request merged**
