### PR TITLE
Set bpfd group permissions appropriately on maps created by bpfd

### PR DESCRIPTION
**Pull request by Billy99**
Maps are being created 0500 (User RW but no Group access), so the Userspace program needs CAP_DAC_SEARCH to read or CAP_DAC_OVERIDE to read/write the maps. Update the map files after program is loaded to grant access the bpfd group.

Update the documents regarding the CAP_BPF and CAP_DAC_OVERRIDE for accessing maps.

Resolves: #349
Resolves: #351

### CODE REVIEW

**Review by anfredette — APPROVED** [review]
This works as intended, and I think this is at least a good short-term solution.  However, I wonder if it would be better to set the permissions closer to where the maps are getting pinned.  I believe this is in the Aya code, but I'm not sure of the details.  I think it would also be good to be able to set the file permissions based on the permissions on the map (e.g., don't allow writes if the map is read-only).

**Review by anfredette — CHANGES_REQUESTED** [review]
I'm withdrawing my approval because of the integration test failure.

I think you may just need to rebase.

**Comment by Billy99** [comment]
> However, I wonder if it would be better to set the permissions closer to where the maps are getting pinned.

I'm not sure if we want something like this in Aya, but maybe. Guess that's a Dave question.

I originally made the function call in `bpf.rs` in `add_multi_attach_program()` and `add_single_attach_program()`, but the `tokio::fs::set_permissions()` was an async call, which means all functions calling it need to be async, all the way up the chain. So I added the call to `set_map_permissions()` at the highest level that was already an async call. Not a rust expert, so I can rework if desired.

**Comment by Billy99** [comment]
> I think it would also be good to be able to set the file permissions based on the permissions on the map (e.g., don't allow writes if the map is read-only).

That information is not in the bpfd gRPC API at the moment. We would need to add it.

**Review by anfredette — APPROVED** [review]
This looks good to me.

**Pull request merged**
